name: Create Doc Issue on Label

on:
  pull_request:
    types: [labeled] # 当 PR 被添加标签时触发

jobs:
  create_issue_if_doc_label:
    # 仅当添加的标签是 'doc' 时才运行此作业
    if: github.event.label.name == 'doc'
    runs-on: ubuntu-latest
    permissions:
      issues: write       # 允许创建 issue
      pull-requests: read # 允许读取 PR 信息 (例如标题和作者)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 通常是好习惯，虽然此特定脚本可能不直接操作文件

      - name: Create Issue from PR
        uses: peter-evans/create-issue-from-file@v5 # 使用一个流行的 action 来创建 issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub 自动提供的 token
          title: "Doc related to ${{ github.event.pull_request.title }}"
          content-filepath: "" # 我们将直接在 body 中定义内容，所以留空
          body: |
            This issue is to track documentation tasks related to Pull Request #${{ github.event.pull_request.number }}.

            **PR Title:** ${{ github.event.pull_request.title }}
            **PR Author:** @${{ github.event.pull_request.user.login }}
            **PR Link:** ${{ github.event.pull_request.html_url }}

            Please ensure all necessary documentation updates are completed.
          assignees: ${{ github.event.pull_request.user.login }} # 指派给 PR 的作者
          # 可选：你也可以给这个新创建的 issue 添加标签
          # labels: documentation, todo
