name: Create Doc Issue on Label

on:
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types: [labeled]

jobs:
  create_issue_if_doc_label:
    if: github.event_name == 'pull_request_target' && github.event.label.name == 'doc'
    runs-on: ubuntu-latest
    permissions:
      issues: write       
      pull-requests: read 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: Create Issue from PR
        uses: dacbd/create-issue-action@v2.0.0 
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          title: "Update doc for #${{github.event.pull_request.number}}, `${{ github.event.pull_request.title }}`"
          body: |
            This issue is to track documentation tasks related to Pull Request #${{ github.event.pull_request.number }}.

            **PR Title:** ${{ github.event.pull_request.title }}
            **PR Author:** @${{ github.event.pull_request.user.login }}
            **PR Link:** ${{ github.event.pull_request.html_url }}

            Please ensure all necessary documentation updates are completed.
          assignees: ${{ github.event.pull_request.user.login }}
